/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A recipe in the catalog
 */
export interface Recipe {
  /**
   * The title of a recipe, displayed to users
   */
  title: string;
  /**
   * The unique identifier for a recipe
   */
  slug: string;
  /**
   * The time spent preparing to cook a recipe (minutes)
   */
  prepTime?: number;
  /**
   * The time spent cooking a recipe (minutes)
   */
  cookTime?: number;
  /**
   * The total time spent before food is ready to eat (minutes; includes prep, cooking, cooling, etc.)
   */
  totalTime?: number;
  /**
   * The components required to cook the recipe
   *
   * @minItems 1
   */
  ingredients: [
    {
      /**
       * The amount of the ingredient required for the recipe
       */
      quantity: number;
      /**
       * The measurement of the quantity required for the recipe
       */
      unit: string;
      /**
       * The common name of the ingredient required for the recipe
       */
      name: string;
      [k: string]: unknown;
    },
    ...{
      /**
       * The amount of the ingredient required for the recipe
       */
      quantity: number;
      /**
       * The measurement of the quantity required for the recipe
       */
      unit: string;
      /**
       * The common name of the ingredient required for the recipe
       */
      name: string;
      [k: string]: unknown;
    }[]
  ];
  /**
   * The steps required to cook the recipe
   *
   * @minItems 1
   */
  steps: [string, ...string[]];
  nutrition?: {
    /**
     * The number of servings of the recipe
     */
    servings: number;
    /**
     * The reccommended amount to eat per serving
     */
    servingSize: {
      /**
       * The numeric value for how much to eat
       */
      quantity: number;
      /**
       * The measurement of the quantity recommended to eat
       */
      unit: string;
      /**
       * The weight (in grams, rounded up) recommended to eat
       */
      weight?: number;
      [k: string]: unknown;
    };
    /**
     * The number of kilocalories per serving
     */
    calories: number;
    /**
     * The values for fats
     */
    fat: {
      /**
       * The total fat (in grams)
       */
      total: number;
      /**
       * The saturated fat (in grams)
       */
      saturated: number;
      /**
       * The trans fat (in grams)
       */
      trans: number;
      [k: string]: unknown;
    };
    /**
     * The value for cholesterol (in milligrams)
     */
    cholesterol: number;
    /**
     * The value for sodium (in milligrams)
     */
    sodium: number;
    /**
     * The values for carbohydrates (sugars)
     */
    carbs: {
      /**
       * The total carbs (in grams)
       */
      total: number;
      /**
       * The dietary fiber (in grams)
       */
      fiber: number;
      /**
       * The sugars
       */
      sugars: {
        /**
         * The total sugars (in grams)
         */
        total: number;
        /**
         * The added sugars (in grams)
         */
        added: number;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    /**
     * The value for protein (in grams)
     */
    protein: number;
    [k: string]: unknown;
  };
  /**
   * Recipe tags, such as allergens, vegetarian, spiciness, kosher/halal, etc.
   *
   * @minItems 1
   */
  tags?: [string, ...string[]];
  [k: string]: unknown;
}